import asyncio
import io
import json
import logging
import os
import signal
import sys
from collections.abc import AsyncIterator
from pathlib import Path
from types import SimpleNamespace

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from procrastinate.schema import SchemaManager
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import NullPool

from app.core.config import DatabaseSettings, LLMSettings, LoggingSettings, Settings, WorkerSettings
from app.core.db import libpq_url
from app.core.logging import configure_logging
from app.worker import (
    DEFAULT_RETRY,
    WorkerGroup,
    app,
    build_connector,
    remove_old_jobs,
    resource_lock,
    retry_stalled_jobs,
    run,
    worker_groups,
)
from tests.conftest import BACKEND_DIR, TEST_DATABASE_URL, alembic_config

VENDORED_SCHEMA = BACKEND_DIR / "migrations" / "sql" / "procrastinate-3.10.0.sql"

# Test-only task, registered on the real app; records its argument in a module variable.
executed: list[str] = []


@app.task(name="tests.record", queue="sync")
async def record(item_id: str) -> None:
    executed.append(item_id)


def test_worker_groups_give_llm_its_own_concurrency() -> None:
    settings = Settings(
        worker=WorkerSettings(concurrency=6), llm=LLMSettings(concurrency=2, max_concurrency=3)
    )

    # Slots up to the maximum; the gateway limits LLM requests to the admin setting.
    assert worker_groups(settings) == [
        WorkerGroup("main", ("sync", "tts", "default"), 6),
        WorkerGroup("llm", ("llm",), 3),
        WorkerGroup("ocr", ("ocr",), 1),
    ]


def test_llm_slots_cover_a_higher_default_concurrency() -> None:
    settings = Settings(llm=LLMSettings(concurrency=6, max_concurrency=2))

    assert worker_groups(settings)[1] == WorkerGroup("llm", ("llm",), 6)


@pytest.mark.parametrize(
    ("queues", "expected"),
    [
        ("llm", [WorkerGroup("llm", ("llm",), 4)]),
        ("sync, tts", [WorkerGroup("main", ("sync", "tts"), 4)]),
        ("ocr", [WorkerGroup("ocr", ("ocr",), 1)]),
    ],
)
def test_worker_queues_from_environment(
    monkeypatch: pytest.MonkeyPatch, queues: str, expected: list[WorkerGroup]
) -> None:
    monkeypatch.setenv("OLLAMAIL_WORKER_QUEUES", queues)

    assert worker_groups(Settings()) == expected


def test_concurrency_from_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("OLLAMAIL_WORKER_CONCURRENCY", "8")
    monkeypatch.setenv("OLLAMAIL_LLM_MAX_CONCURRENCY", "3")
    monkeypatch.setenv("OLLAMAIL_SEARCH_OCR_CONCURRENCY", "2")

    groups = worker_groups(Settings())

    assert [(g.name, g.concurrency) for g in groups] == [("main", 8), ("llm", 3), ("ocr", 2)]


def test_unknown_queue_is_rejected(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("OLLAMAIL_WORKER_QUEUES", "sync,mail")

    with pytest.raises(ValueError, match="queues"):
        Settings(worker=WorkerSettings())


def test_resource_lock_is_per_resource() -> None:
    assert resource_lock("mailbox", "a") == "mailbox:a"
    assert resource_lock("mailbox", "a") != resource_lock("mailbox", "b")


def test_default_retry_backs_off_exponentially() -> None:
    assert DEFAULT_RETRY.max_attempts == 8
    waits = [DEFAULT_RETRY.wait + DEFAULT_RETRY.exponential_wait ** (n + 1) for n in range(4)]
    assert waits == [2, 4, 8, 16]


def test_libpq_url_drops_driver() -> None:
    settings = DatabaseSettings.model_validate({"url": "postgresql+asyncpg://u:p@db:5432/x"})

    assert libpq_url(settings) == "postgresql://u:p@db:5432/x"


def test_periodic_cleanup_is_registered() -> None:
    periodic = {task.periodic_id: task for task in app.periodic_registry.periodic_tasks.values()}

    assert periodic["remove_old_jobs"].task is remove_old_jobs
    assert remove_old_jobs.queue == "default"
    assert periodic["retry_stalled_jobs"].task is retry_stalled_jobs
    assert retry_stalled_jobs.queue == "default"


def test_vendored_schema_matches_installed_procrastinate() -> None:
    """Fails after a Procrastinate upgrade that changes the schema: add an Alembic migration
    applying the new files from procrastinate/sql/migrations/, then update this check."""
    vendored = VENDORED_SCHEMA.read_text(encoding="utf-8")
    body = vendored.split("\n\n", 1)[1]

    assert body == SchemaManager.get_schema()


def test_procrastinate_logs_hide_task_arguments() -> None:
    stream = io.StringIO()
    configure_logging(LoggingSettings(level="DEBUG", format="json"), stream=stream)
    logging.getLogger("procrastinate.worker").info(
        "Job %s succeeded",
        "record[1](item_id='Quarterly numbers')",
        extra={
            "action": "job_success",
            "job": {
                "id": 1,
                "task_name": "tests.record",
                "task_kwargs": {"item_id": "Quarterly numbers"},
                "call_string": "record[1](item_id='Quarterly numbers')",
            },
            "result": "Quarterly numbers",
        },
    )

    output = stream.getvalue()
    assert "Quarterly numbers" not in output
    entry = json.loads(output)
    assert entry["event"] == "job_success"
    assert entry["job"] == {"id": 1, "task_name": "tests.record"}


# --- Integration tests against PostgreSQL -------------------------------------------------


async def _execute(statement: str) -> list[tuple[object, ...]]:
    engine = create_async_engine(TEST_DATABASE_URL, poolclass=NullPool)
    async with engine.begin() as connection:
        result = await connection.execute(text(statement))
        rows = [tuple(row) for row in result] if result.returns_rows else []
    await engine.dispose()
    return rows


async def _job_status(job_id: int) -> str:
    rows = await _execute(f"SELECT status FROM procrastinate_jobs WHERE id = {int(job_id)}")
    return str(rows[0][0])


async def _wait_for_status(job_id: int, status: str) -> None:
    for _ in range(200):
        if await _job_status(job_id) == status:
            return
        await asyncio.sleep(0.1)
    raise AssertionError(f"job {job_id} did not reach {status!r}")


@pytest.fixture
async def queue_database(migrated_database: str) -> AsyncIterator[DatabaseSettings]:
    """Empty job tables; Procrastinate commits, so the tests clean up after themselves."""
    settings = DatabaseSettings.model_validate({"url": migrated_database})
    await _execute("DELETE FROM procrastinate_jobs")
    with app.replace_connector(build_connector(settings)):
        yield settings
    await _execute("DELETE FROM procrastinate_jobs")


@pytest.mark.db
async def test_worker_runs_deferred_task(queue_database: DatabaseSettings) -> None:
    executed.clear()
    async with app.open_async():
        job_id = await record.defer_async(item_id="item-1")

    stop = asyncio.Event()
    settings = Settings(database=queue_database, worker=WorkerSettings(queues=["sync"]))
    worker = asyncio.create_task(run(settings, stop))
    try:
        await _wait_for_status(job_id, "succeeded")
    finally:
        stop.set()
        await asyncio.wait_for(worker, timeout=10)

    assert executed == ["item-1"]


@pytest.mark.db
async def test_worker_writes_heartbeat_and_closes_the_shared_engine(
    queue_database: DatabaseSettings, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from app.core import db
    from app.core.heartbeat import check

    monkeypatch.setattr(db, "_process_database", None)
    heartbeat = tmp_path / "heartbeat"
    worker_settings = WorkerSettings(
        queues=["sync"], heartbeat_file=heartbeat, heartbeat_interval_seconds=1
    )
    settings = Settings(database=queue_database, worker=worker_settings)
    stop = asyncio.Event()
    worker = asyncio.create_task(run(settings, stop))
    try:
        for _ in range(100):
            if heartbeat.exists():
                break
            await asyncio.sleep(0.05)
        assert check(worker_settings)
        db.process_database()  # created by the first job
    finally:
        stop.set()
        await asyncio.wait_for(worker, timeout=10)

    assert not heartbeat.exists()
    assert db._process_database is None


@pytest.mark.db
async def test_queueing_lock_prevents_duplicate_jobs(queue_database: DatabaseSettings) -> None:
    from procrastinate.exceptions import AlreadyEnqueued

    lock = resource_lock("mailbox", "m1")
    async with app.open_async():
        await record.configure(queueing_lock=lock).defer_async(item_id="a")
        with pytest.raises(AlreadyEnqueued):
            await record.configure(queueing_lock=lock).defer_async(item_id="b")


@pytest.mark.db
async def test_worker_process_runs_task_and_stops_on_sigterm(
    queue_database: DatabaseSettings,
) -> None:
    async with app.open_async():
        job_id = await remove_old_jobs.defer_async(timestamp=0)

    env = {
        **os.environ,
        "OLLAMAIL_DATABASE_URL": queue_database.url.get_secret_value(),
        "OLLAMAIL_LOG_FORMAT": "json",
    }
    process = await asyncio.create_subprocess_exec(
        sys.executable,
        "-m",
        "app.worker",
        cwd=Path(BACKEND_DIR),
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )
    try:
        await _wait_for_status(job_id, "succeeded")
        assert await _execute("SELECT count(*) FROM procrastinate_workers") == [(3,)]

        process.send_signal(signal.SIGTERM)
        output, _ = await asyncio.wait_for(process.communicate(), timeout=20)
    finally:
        if process.returncode is None:
            process.kill()
            await process.wait()

    assert process.returncode == 0
    events = [json.loads(line)["event"] for line in output.decode().splitlines()]
    assert events[-1] == "worker_stopped"
    # Graceful shutdown unregisters the workers.
    assert await _execute("SELECT count(*) FROM procrastinate_workers") == [(0,)]


@pytest.fixture
async def registered_workers(queue_database: DatabaseSettings) -> AsyncIterator[list[int]]:
    """IDs of workers a test registers by hand; removed afterwards (other tests count
    the rows of ``procrastinate_workers``)."""
    worker_ids: list[int] = []
    yield worker_ids
    for worker_id in worker_ids:
        await _execute(f"DELETE FROM procrastinate_workers WHERE id = {int(worker_id)}")


async def _start_job_on_dead_worker(lock: str, worker_ids: list[int]) -> int:
    """A ``tests.record`` job in ``doing`` whose worker stopped sending heartbeats, as
    after an OOM kill."""
    async with app.open_async():
        job_id = await record.configure(lock=lock).defer_async(item_id="stalled")
        worker_id = await app.job_manager.register_worker()
        worker_ids.append(worker_id)
        job = await app.job_manager.fetch_job(["sync"], worker_id)
    assert job is not None and job.id == job_id
    await _execute(
        "UPDATE procrastinate_workers SET last_heartbeat = now() - interval '10 minutes' "
        f"WHERE id = {int(worker_id)}"
    )
    return job_id


async def _run_default_queue_once() -> None:
    from procrastinate.periodic import PeriodicRegistry

    registry, app.periodic_registry = app.periodic_registry, PeriodicRegistry()
    try:
        async with app.open_async():
            await app.run_worker_async(
                queues=["default"], wait=False, install_signal_handlers=False, listen_notify=False
            )
    finally:
        app.periodic_registry = registry


@pytest.mark.db
async def test_stalled_job_of_a_dead_worker_is_retried(registered_workers: list[int]) -> None:
    lock = resource_lock("mailbox", "m-stalled")
    stalled = await _start_job_on_dead_worker(lock, registered_workers)
    async with app.open_async():
        # The stalled job holds the mailbox lock: a new job for it could never start.
        waiting = await record.configure(lock=lock).defer_async(item_id="next")
        await retry_stalled_jobs.defer_async(timestamp=0)

    await _run_default_queue_once()

    assert await _job_status(stalled) == "todo"
    executed.clear()
    async with app.open_async():
        await app.run_worker_async(
            queues=["sync"], wait=False, install_signal_handlers=False, listen_notify=False
        )
    assert sorted(executed) == ["next", "stalled"]
    assert await _job_status(waiting) == "succeeded"


@pytest.mark.db
async def test_running_job_with_live_worker_is_left_alone(registered_workers: list[int]) -> None:
    async with app.open_async():
        await record.defer_async(item_id="busy")
        worker_id = await app.job_manager.register_worker()
        registered_workers.append(worker_id)
        job = await app.job_manager.fetch_job(["sync"], worker_id)
        assert job is not None and job.id is not None
        await retry_stalled_jobs.defer_async(timestamp=0)

    await _run_default_queue_once()

    assert await _job_status(job.id) == "doing"


@pytest.mark.db
async def test_autogenerate_ignores_procrastinate_tables(migrated_database: str) -> None:
    # Without the filter in migrations/env.py autogenerate would drop the job tables.
    # Other test modules register test-only models, so only Procrastinate diffs count.
    try:
        await asyncio.to_thread(command.check, alembic_config(migrated_database))
    except AutogenerateDiffsDetected as exc:
        assert "procrastinate" not in str(exc)


@pytest.mark.db
async def test_succeeded_jobs_are_removed_sooner_than_failed_ones(
    queue_database: DatabaseSettings, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        "app.worker.get_settings",
        lambda: Settings(
            worker=WorkerSettings(job_retention_hours=24, failed_job_retention_hours=72)
        ),
    )
    async with app.open_async():
        jobs = {
            (status, hours): await record.defer_async(item_id=f"{status}-{hours}")
            for status, hours in (
                ("succeeded", 2),
                ("succeeded", 30),
                ("failed", 30),
                ("failed", 80),
                ("todo", 80),
            )
        }
    for (status, hours), job_id in jobs.items():
        await _execute(
            f"UPDATE procrastinate_jobs SET status = '{status}' WHERE id = {int(job_id)}"
        )
        await _execute(
            f"UPDATE procrastinate_events SET at = now() - interval '{hours} hours' "
            f"WHERE job_id = {int(job_id)}"
        )

    async with app.open_async():
        await remove_old_jobs(SimpleNamespace(app=app), timestamp=0)  # type: ignore[arg-type]

    left = {row[0] for row in await _execute("SELECT id FROM procrastinate_jobs")}
    assert left == {jobs[("succeeded", 2)], jobs[("failed", 30)], jobs[("todo", 80)]}


def test_old_jobs_are_removed_hourly() -> None:
    periodic = {task.periodic_id: task for task in app.periodic_registry.periodic_tasks.values()}

    assert periodic["remove_old_jobs"].cron == "17 * * * *"
