/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Sign in with a local account.
         */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the current session (also without a valid session).
         */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The signed-in user.
         */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Change display name, language or time zone of the own account.
         */
        patch: operations["auth_update_me"];
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Providers
         * @description Sign-in options for the login page.
         */
        get: operations["auth_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a local account (role ``user``) and sign in, if self-registration is on.
         */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description The own active sessions, most recently used first.
         */
        get: operations["auth_list_sessions"];
        put?: never;
        post?: never;
        /**
         * Revoke Sessions
         * @description Sign out all other sessions, or all sessions with ``include_current=true``.
         */
        delete: operations["auth_revoke_sessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Session
         * @description Sign out one of the own sessions.
         */
        delete: operations["auth_revoke_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Stream the current user's events. Each SSE ``event`` is the event type, ``data``
         *     the JSON-encoded event.
         */
        get: operations["events_stream_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe: reports that the process is up.
         */
        get: operations["health_healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mailboxes
         * @description The user's mailboxes with their sync status.
         */
        get: operations["mailboxes_list_mailboxes"];
        put?: never;
        /**
         * Create Mailbox
         * @description Add a mailbox. The connection is tested first; then the initial import starts
         *     (unless ``sync_enabled`` is false).
         */
        post: operations["mailboxes_create_mailbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/autodiscover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autodiscover
         * @description Connection suggestions for an address (known providers, else guesses from the
         *     domain). Offline; nothing is looked up or stored. The address travels in the body so
         *     it never appears in access logs.
         */
        post: operations["mailboxes_autodiscover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Mailbox Connection
         * @description Connect and list the folders without saving anything. A failed test is a normal
         *     result (``ok: false`` with an error code), not an HTTP error.
         */
        post: operations["mailboxes_test_mailbox_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/{mailbox_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mailbox */
        get: operations["mailboxes_get_mailbox"];
        put?: never;
        post?: never;
        /**
         * Delete Mailbox
         * @description Remove the mailbox and everything derived from it: mails, attachments (including
         *     the files), threads, folders, sync state, processing results, todos, triage results
         *     and the search index. Hard delete; returns what was removed as confirmation.
         */
        delete: operations["mailboxes_delete_mailbox"];
        options?: never;
        head?: never;
        /**
         * Update Mailbox
         * @description Rename, change connection settings or credentials (tested before saving), change
         *     the import period or excluded folder roles, pause (``sync_enabled: false``) or resume
         *     syncing.
         */
        patch: operations["mailboxes_update_mailbox"];
        trace?: never;
    };
    "/mailboxes/{mailbox_id}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Folders
         * @description Folders known from the last sync, with selection and per-folder sync status.
         *     Before the first sync, use the folder list of the connection test.
         */
        get: operations["mailboxes_list_folders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Select Folders
         * @description Choose which folders are synced. Deselected folders keep their stored mails;
         *     newly selected folders are imported with the next sync (requested right away).
         */
        patch: operations["mailboxes_select_folders"];
        trace?: never;
    };
    "/mailboxes/{mailbox_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mailbox Status
         * @description Sync status only (cheap to poll as a fallback to SSE).
         */
        get: operations["mailboxes_get_mailbox_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/{mailbox_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Mailbox
         * @description Start a sync now. Progress arrives as ``mailbox.sync`` events.
         */
        post: operations["mailboxes_sync_mailbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe: 200 if all registered checks pass, otherwise 503.
         */
        get: operations["health_readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Admin
         * @description Create the first admin and sign them in. Only possible while no user exists.
         */
        post: operations["setup_create_admin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Whether the instance has been set up (an admin exists).
         */
        get: operations["setup_get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Todos
         * @description Own todos, earliest due date first (todos without due date last).
         */
        get: operations["todos_list_todos"];
        put?: never;
        /**
         * Create Todo
         * @description Create a todo by hand, optionally linked to one of the user's mails.
         */
        post: operations["todos_create_todo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{todo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Todo */
        get: operations["todos_get_todo"];
        put?: never;
        post?: never;
        /** Delete Todo */
        delete: operations["todos_delete_todo"];
        options?: never;
        head?: never;
        /**
         * Update Todo
         * @description Edit a todo or change its status (open, done, dismissed).
         */
        patch: operations["todos_update_todo"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description All users, ordered by e-mail address.
         */
        get: operations["users_list_users"];
        put?: never;
        /**
         * Create User
         * @description Create a local account with an initial password.
         */
        post: operations["users_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthProviderInfo */
        AuthProviderInfo: {
            /** Display Name */
            display_name: string;
            kind: components["schemas"]["AuthProviderKind"];
            /** Name */
            name: string;
        };
        /**
         * AuthProviderKind
         * @enum {string}
         */
        AuthProviderKind: "password" | "redirect";
        /** AuthProviders */
        AuthProviders: {
            /** Local Login */
            local_login: boolean;
            /** Local Registration */
            local_registration: boolean;
            /** Providers */
            providers: components["schemas"]["AuthProviderInfo"][];
        };
        /** AutodiscoverRequest */
        AutodiscoverRequest: {
            /** Address */
            address: string;
        };
        /** AutodiscoverResult */
        AutodiscoverResult: {
            /** Suggestions */
            suggestions: components["schemas"]["AutodiscoverSuggestion"][];
        };
        /** AutodiscoverSuggestion */
        AutodiscoverSuggestion: {
            /** Hints */
            hints: components["schemas"]["Hint"][];
            /** Provider Settings */
            provider_settings: {
                [key: string]: unknown;
            };
            source: components["schemas"]["Source"];
            type: components["schemas"]["MailboxType"];
        };
        /** ConnectionTestResult */
        ConnectionTestResult: {
            /** Error */
            error?: string | null;
            /** Folders */
            folders?: components["schemas"]["RemoteFolderRead"][];
            /** Ok */
            ok: boolean;
        };
        /**
         * FolderKind
         * @enum {string}
         */
        FolderKind: "folder" | "label";
        /** FolderRead */
        FolderRead: {
            /** Excluded By Role */
            excluded_by_role: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Import Pending */
            import_pending: boolean;
            kind: components["schemas"]["FolderKind"];
            /** Last Error */
            last_error: string | null;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Message Count */
            message_count: number;
            /** Name */
            name: string;
            /** Remote Id */
            remote_id: string;
            role: components["schemas"]["FolderRole"] | null;
            /** Sync Enabled */
            sync_enabled: boolean;
            /** Synced */
            synced: boolean;
        };
        /**
         * FolderRole
         * @description Special-use roles (RFC 6154 for IMAP, well-known folders in Graph, system labels
         *     in Gmail).
         * @enum {string}
         */
        FolderRole: "inbox" | "sent" | "drafts" | "trash" | "junk" | "archive" | "all";
        /** FolderSelection */
        FolderSelection: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sync Enabled */
            sync_enabled: boolean;
        };
        /** FolderSelectionUpdate */
        FolderSelectionUpdate: {
            /** Folders */
            folders: components["schemas"]["FolderSelection"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * Hint
         * @description Machine-readable notes for the UI (translated there).
         * @enum {string}
         */
        Hint: "app_password" | "enable_imap" | "oauth_required" | "mail_password" | "guessed";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MailboxConnection
         * @description Everything needed to connect to a mailbox.
         */
        MailboxConnection: {
            /** Address */
            address: string;
            /** Credentials */
            credentials?: {
                [key: string]: string;
            };
            /** Provider Settings */
            provider_settings?: {
                [key: string]: unknown;
            };
            type: components["schemas"]["MailboxType"];
        };
        /** MailboxCreate */
        MailboxCreate: {
            /** Address */
            address: string;
            /** Credentials */
            credentials?: {
                [key: string]: string;
            };
            /** Display Name */
            display_name?: string | null;
            /** Provider Settings */
            provider_settings?: {
                [key: string]: unknown;
            };
            /**
             * Sync Enabled
             * @default true
             */
            sync_enabled: boolean;
            sync_settings?: components["schemas"]["SyncSettings"];
            type: components["schemas"]["MailboxType"];
        };
        /**
         * MailboxDeleted
         * @description Confirmation of a removal: the mailbox and all data derived from it (mails,
         *     attachments and their files, threads, folders, sync state, processing results, todos,
         *     triage results, search index) are deleted.
         */
        MailboxDeleted: {
            /** Attachments */
            attachments: number;
            /**
             * Deleted
             * @default true
             * @constant
             */
            deleted: true;
            /**
             * Mailbox Id
             * Format: uuid
             */
            mailbox_id: string;
            /** Messages */
            messages: number;
        };
        /** MailboxRead */
        MailboxRead: {
            /** Address */
            address: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Has Credentials */
            has_credentials: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Shared */
            is_shared: boolean;
            /** Provider Settings */
            provider_settings: {
                [key: string]: unknown;
            };
            status: components["schemas"]["MailboxSyncStatus"];
            /** Sync Enabled */
            sync_enabled: boolean;
            sync_settings: components["schemas"]["SyncSettings"];
            type: components["schemas"]["MailboxType"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MailboxSyncStatus
         * @description ``phase`` summarises the fields: ``paused`` (sync disabled), ``error`` (the last sync
         *     failed for the whole mailbox), ``syncing`` (a sync job is queued or running),
         *     ``pending`` (never synced), ``importing`` (initial import of some folder unfinished),
         *     else ``idle``.
         */
        MailboxSyncStatus: {
            /** Folders Failed */
            folders_failed: number;
            /** Folders Imported */
            folders_imported: number;
            /** Folders Total */
            folders_total: number;
            /** Last Error */
            last_error: string | null;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Message Count */
            message_count: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "paused" | "pending" | "importing" | "syncing" | "idle" | "error";
            /** Sync Queued */
            sync_queued: boolean;
        };
        /**
         * MailboxType
         * @enum {string}
         */
        MailboxType: "imap" | "graph" | "gmail";
        /**
         * MailboxUpdate
         * @description Fields to change; omitted fields stay. Changed connection settings or credentials
         *     are tested before they are saved. ``sync_enabled`` pauses or resumes syncing.
         */
        MailboxUpdate: {
            /** Credentials */
            credentials?: {
                [key: string]: string;
            } | null;
            /** Display Name */
            display_name?: string | null;
            /** Provider Settings */
            provider_settings?: {
                [key: string]: unknown;
            } | null;
            /** Sync Enabled */
            sync_enabled?: boolean | null;
            sync_settings?: components["schemas"]["SyncSettingsUpdate"] | null;
        };
        /**
         * ProfileUpdate
         * @description Fields a user may change on their own account.
         */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Language */
            language?: ("de" | "en") | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** ReadinessStatus */
        ReadinessStatus: {
            /** Checks */
            checks: {
                [key: string]: "ok" | "failed";
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "de" | "en";
            /** Password */
            password: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /**
         * RemoteFolderRead
         * @description A folder as reported by the server (connection test).
         */
        RemoteFolderRead: {
            kind: components["schemas"]["FolderKind"];
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Remote Id */
            remote_id: string;
            role: components["schemas"]["FolderRole"] | null;
        };
        /** SessionRead */
        SessionRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current */
            current: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Provider */
            provider: string;
            /** User Agent */
            user_agent: string | null;
        };
        /** SetupRequest */
        SetupRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "de" | "en";
            /** Password */
            password: string;
            /** Setup Token */
            setup_token: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** SetupStatus */
        SetupStatus: {
            /** Initialized */
            initialized: boolean;
        };
        /**
         * Source
         * @enum {string}
         */
        Source: "known" | "guess";
        /** SyncRequestResult */
        SyncRequestResult: {
            /** Queued */
            queued: boolean;
        };
        /**
         * SyncSettings
         * @description ``Mailbox.sync_settings``. Unset values fall back to instance settings.
         */
        SyncSettings: {
            /** Excluded Folders */
            excluded_folders?: string[];
            /** Excluded Roles */
            excluded_roles?: components["schemas"]["FolderRole"][];
            /** Initial Sync Days */
            initial_sync_days?: number | null;
            /**
             * Poll Interval Seconds
             * @default 300
             */
            poll_interval_seconds: number;
        };
        /**
         * SyncSettingsUpdate
         * @description Changes to ``SyncSettings``; omitted fields stay, ``initial_sync_days: null`` falls
         *     back to the instance default. The import period applies to folders whose initial
         *     import has not started yet.
         */
        SyncSettingsUpdate: {
            /** Excluded Folders */
            excluded_folders?: string[] | null;
            /** Excluded Roles */
            excluded_roles?: components["schemas"]["FolderRole"][] | null;
            /** Initial Sync Days */
            initial_sync_days?: number | null;
            /** Poll Interval Seconds */
            poll_interval_seconds?: number | null;
        };
        /**
         * TodoCreate
         * @description A todo created by the user, optionally linked to one of their mails.
         */
        TodoCreate: {
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Message Id */
            message_id?: string | null;
            /** @default normal */
            priority: components["schemas"]["TodoPriority"];
            /** Title */
            title: string;
        };
        /**
         * TodoPriority
         * @enum {string}
         */
        TodoPriority: "high" | "normal" | "low";
        /** TodoRead */
        TodoRead: {
            /** Completed At */
            completed_at: string | null;
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Done Suggested */
            done_suggested: boolean;
            /** Due Date */
            due_date: string | null;
            /** External Refs */
            external_refs: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Edited */
            is_edited: boolean;
            /** Is Manual */
            is_manual: boolean;
            /** Mailbox Id */
            mailbox_id: string | null;
            /** Message Id */
            message_id: string | null;
            priority: components["schemas"]["TodoPriority"];
            status: components["schemas"]["TodoStatus"];
            /** Thread Id */
            thread_id: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TodoStatus
         * @enum {string}
         */
        TodoStatus: "open" | "done" | "dismissed";
        /**
         * TodoUpdate
         * @description Fields to change; omitted fields stay. ``null`` clears description and due date.
         */
        TodoUpdate: {
            /** Description */
            description?: string | null;
            /** Done Suggested */
            done_suggested?: boolean | null;
            /** Due Date */
            due_date?: string | null;
            priority?: components["schemas"]["TodoPriority"] | null;
            status?: components["schemas"]["TodoStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * UserCreate
         * @description A new local account (admin).
         */
        UserCreate: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "de" | "en";
            /** Password */
            password: string;
            /** @default user */
            role: components["schemas"]["UserRole"];
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Language */
            language: string;
            /** Last Login At */
            last_login_at: string | null;
            role: components["schemas"]["UserRole"];
            /** Timezone */
            timezone: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "user";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Wrong credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many attempts (rate limit or account lockout) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProviders"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Registration is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail address taken or instance not set up */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many attempts (rate limit or account lockout) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_revoke_sessions: {
        parameters: {
            query?: {
                include_current?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_revoke_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_stream_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream of `Event` objects for the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        /** Ids */
                        ids?: {
                            [key: string]: string | number;
                        };
                        /** Status */
                        status?: string | null;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description The event listener is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    mailboxes_list_mailboxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxRead"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailboxes_create_mailbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailboxCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mailbox already added */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request, unavailable mailbox type or failed connection test */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailboxes_autodiscover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutodiscoverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutodiscoverResult"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mailboxes_test_mailbox_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailboxConnection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request, unavailable mailbox type or failed connection test */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailboxes_get_mailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mailboxes_delete_mailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxDeleted"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mailboxes_update_mailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailboxUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request, unavailable mailbox type or failed connection test */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailboxes_list_folders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mailboxes_select_folders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderSelectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mailboxes_get_mailbox_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxSyncStatus"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mailboxes_sync_mailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRequestResult"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such mailbox */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Syncing is paused */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
    setup_create_admin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Wrong setup token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The instance is already set up */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    todos_list_todos: {
        parameters: {
            query?: {
                /** @description Repeat for several. */
                status?: components["schemas"]["TodoStatus"][] | null;
                mailbox_id?: string | null;
                /** @description Due on or before this day. */
                due_before?: string | null;
                /** @description Due on or after this day. */
                due_after?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoRead"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    todos_create_todo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Linked message not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    todos_get_todo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such todo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    todos_delete_todo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such todo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    todos_update_todo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such todo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail address taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
