/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as AdminAiRouteImport } from './routes/admin_.ai'
import { Route as AdminAuditRouteImport } from './routes/admin_.audit'
import { Route as AdminCategoriesRouteImport } from './routes/admin_.categories'
import { Route as AdminRetentionRouteImport } from './routes/admin_.retention'
import { Route as AdminRoleMappingRouteImport } from './routes/admin_.role-mapping'
import { Route as AdminSignInRouteImport } from './routes/admin_.sign-in'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as DigestSettingsRouteImport } from './routes/digest_.settings'
import { Route as SettingsCategoriesRouteImport } from './routes/settings_.categories'
import { Route as SettingsMailboxesRouteImport } from './routes/settings_.mailboxes'
import { Route as SettingsMailboxesNewRouteImport } from './routes/settings_.mailboxes_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin_/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin_/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin_/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetentionRoute = AdminRetentionRouteImport.update({
  id: '/admin_/retention',
  path: '/admin/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoleMappingRoute = AdminRoleMappingRouteImport.update({
  id: '/admin_/role-mapping',
  path: '/admin/role-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/admin_/sign-in',
  path: '/admin/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestSettingsRoute = DigestSettingsRouteImport.update({
  id: '/digest_/settings',
  path: '/digest/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/settings_/categories',
  path: '/settings/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMailboxesRoute = SettingsMailboxesRouteImport.update({
  id: '/settings_/mailboxes',
  path: '/settings/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMailboxesNewRoute = SettingsMailboxesNewRouteImport.update({
  id: '/settings_/mailboxes_/new',
  path: '/settings/mailboxes/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/digest': typeof DigestRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/role-mapping': typeof AdminRoleMappingRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/users': typeof AdminUsersRoute
  '/digest/settings': typeof DigestSettingsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/mailboxes': typeof SettingsMailboxesRoute
  '/settings/mailboxes/new': typeof SettingsMailboxesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/digest': typeof DigestRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/role-mapping': typeof AdminRoleMappingRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/users': typeof AdminUsersRoute
  '/digest/settings': typeof DigestSettingsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/mailboxes': typeof SettingsMailboxesRoute
  '/settings/mailboxes/new': typeof SettingsMailboxesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/digest': typeof DigestRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/admin_/ai': typeof AdminAiRoute
  '/admin_/audit': typeof AdminAuditRoute
  '/admin_/categories': typeof AdminCategoriesRoute
  '/admin_/retention': typeof AdminRetentionRoute
  '/admin_/role-mapping': typeof AdminRoleMappingRoute
  '/admin_/sign-in': typeof AdminSignInRoute
  '/admin_/users': typeof AdminUsersRoute
  '/digest_/settings': typeof DigestSettingsRoute
  '/settings_/categories': typeof SettingsCategoriesRoute
  '/settings_/mailboxes': typeof SettingsMailboxesRoute
  '/settings_/mailboxes_/new': typeof SettingsMailboxesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/digest'
    | '/inbox'
    | '/invite'
    | '/login'
    | '/search'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/retention'
    | '/admin/role-mapping'
    | '/admin/sign-in'
    | '/admin/users'
    | '/digest/settings'
    | '/settings/categories'
    | '/settings/mailboxes'
    | '/settings/mailboxes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/digest'
    | '/inbox'
    | '/invite'
    | '/login'
    | '/search'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/retention'
    | '/admin/role-mapping'
    | '/admin/sign-in'
    | '/admin/users'
    | '/digest/settings'
    | '/settings/categories'
    | '/settings/mailboxes'
    | '/settings/mailboxes/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/digest'
    | '/inbox'
    | '/invite'
    | '/login'
    | '/search'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/admin_/ai'
    | '/admin_/audit'
    | '/admin_/categories'
    | '/admin_/retention'
    | '/admin_/role-mapping'
    | '/admin_/sign-in'
    | '/admin_/users'
    | '/digest_/settings'
    | '/settings_/categories'
    | '/settings_/mailboxes'
    | '/settings_/mailboxes_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DigestRoute: typeof DigestRoute
  InboxRoute: typeof InboxRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TasksRoute: typeof TasksRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminRetentionRoute: typeof AdminRetentionRoute
  AdminRoleMappingRoute: typeof AdminRoleMappingRoute
  AdminSignInRoute: typeof AdminSignInRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DigestSettingsRoute: typeof DigestSettingsRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsMailboxesRoute: typeof SettingsMailboxesRoute
  SettingsMailboxesNewRoute: typeof SettingsMailboxesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/ai': {
      id: '/admin_/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/audit': {
      id: '/admin_/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/categories': {
      id: '/admin_/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/retention': {
      id: '/admin_/retention'
      path: '/admin/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AdminRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/role-mapping': {
      id: '/admin_/role-mapping'
      path: '/admin/role-mapping'
      fullPath: '/admin/role-mapping'
      preLoaderRoute: typeof AdminRoleMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/sign-in': {
      id: '/admin_/sign-in'
      path: '/admin/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest_/settings': {
      id: '/digest_/settings'
      path: '/digest/settings'
      fullPath: '/digest/settings'
      preLoaderRoute: typeof DigestSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/categories': {
      id: '/settings_/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/mailboxes': {
      id: '/settings_/mailboxes'
      path: '/settings/mailboxes'
      fullPath: '/settings/mailboxes'
      preLoaderRoute: typeof SettingsMailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/mailboxes_/new': {
      id: '/settings_/mailboxes_/new'
      path: '/settings/mailboxes/new'
      fullPath: '/settings/mailboxes/new'
      preLoaderRoute: typeof SettingsMailboxesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DigestRoute: DigestRoute,
  InboxRoute: InboxRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TasksRoute: TasksRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminRetentionRoute: AdminRetentionRoute,
  AdminRoleMappingRoute: AdminRoleMappingRoute,
  AdminSignInRoute: AdminSignInRoute,
  AdminUsersRoute: AdminUsersRoute,
  DigestSettingsRoute: DigestSettingsRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsMailboxesRoute: SettingsMailboxesRoute,
  SettingsMailboxesNewRoute: SettingsMailboxesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
