"""add session authenticated_at

Revision ID: 23b02eb66722
Revises: 7150e49202cb
Create Date: 2026-10-03 00:07:22.621439+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "23b02eb66722"
down_revision: str | Sequence[str] | None = "7150e49202cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_sessions",
        sa.Column(
            "authenticated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    # Existing sessions count as authenticated when they were created, not now: sensitive
    # actions in them need a new confirmation (#144).
    op.execute("UPDATE auth_sessions SET authenticated_at = created_at")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_sessions", "authenticated_at")
    # ### end Alembic commands ###
